Tarefa 1

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [ ]:
def print_image(caminho):
    img = mpimg.imread(caminho)
    plt.imshow(img)
    plt.show()

In [ ]:
print_image('/Users/luizeduardosantos/Documents/Turing/projeto-trainee-cv/Dataset Trainee Oficial Top/Darth Vader/0b734b6153da8cc6f27aebaefd083a135581e6d7.jpg')

In [1]:
import numpy as np
import cv2

In [ ]:
def print_image2(caminho):
    img = cv2.imread(caminho,0)
    cv2.imshow("image", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [ ]:
#Problema - fica rodando sem parar
#print_image2('/Users/luizeduardosantos/Documents/Turing/projeto-trainee-cv/Dataset Trainee Oficial Top/Darth Vader/0c7ed5773df0c92a95a543eeba9a077979a5256a.jpg')

In [ ]:
#from PIL import image
#im = Image.open(/Users/luizeduardosantos/Documents/Turing/projeto-trainee-cv/Dataset Trainee Oficial Top/Darth Vader/0cda4f48a21354afa1d858690473e872fe34d6f4.jpg)
#im.show()

TAREFA 2

In [2]:
# usando numpy
img = cv2.imread('/Users/luizeduardosantos/Documents/Turing/projeto-trainee-cv/Dataset Trainee Oficial Top/Darth Vader/0c7ed5773df0c92a95a543eeba9a077979a5256a.jpg', 0)
def to_bw(img,threshold):
    for i in range (np.shape(img)[0]):
        for j in range (np.shape(img)[1]):
            if img[i][j]< threshold:
                img[i][j] = 0
            else:
                img[i][j]=255
to_bw(img,128)
img

array([[255, 255, 255, ...,   0,   0,   0],
       [255, 255, 255, ...,   0,   0,   0],
       [255, 255, 255, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [ ]:
# usando opencv
img = cv2.imread('/Users/luizeduardosantos/Documents/Turing/projeto-trainee-cv/Dataset Trainee Oficial Top/Darth Vader/0c7ed5773df0c92a95a543eeba9a077979a5256a.jpg', 0)
img_preto_branco = cv2.threshold(img, 128, 255, cv2.THRESH_BINARY)[1]
img_preto_branco

Tarefa 3

In [2]:
#flip
img = cv2.imread('/Users/luizeduardosantos/Documents/Turing/projeto-trainee-cv/Dataset Trainee Oficial Top/Darth Vader/0c7ed5773df0c92a95a543eeba9a077979a5256a.jpg', 1)
flipped=np.empty(np.shape(img))
linhas=np.shape(img)[0]-1
colunas=np.shape(img)[1]-1

for i in range (linhas):
    for j in range (colunas):
         flipped[linhas-i][colunas-j]=img[i][j]
for j in range (colunas):
    for i in range (linhas):
        flipped[linhas-i][colunas-j]=img[i][j]

        
        #np.flip(img)

In [3]:
flipped

array([[[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [ 39.,  29.,  29.],
        [ 40.,  30.,  30.],
        ...,
        [ 13.,  11.,  10.],
        [ 13.,  11.,  10.],
        [ 10.,   8.,   7.]],

       [[  0.,   0.,   0.],
        [ 39.,  29.,  29.],
        [ 40.,  30.,  30.],
        ...,
        [ 13.,  11.,  10.],
        [ 13.,  11.,  10.],
        [ 10.,   8.,   7.]],

       ...,

       [[  0.,   0.,   0.],
        [  3.,   1.,   1.],
        [  3.,   1.,   1.],
        ...,
        [175., 169., 162.],
        [174., 168., 161.],
        [173., 167., 160.]],

       [[  0.,   0.,   0.],
        [  3.,   1.,   1.],
        [  3.,   1.,   1.],
        ...,
        [174., 166., 159.],
        [172., 164., 157.],
        [171., 163., 156.]],

       [[  0.,   0.,   0.],
        [  3.,   1.,   1.],
        [  3.,  

In [4]:
img

array([[[168, 160, 153],
        [169, 161, 154],
        [171, 163, 156],
        ...,
        [  3,   1,   1],
        [  3,   1,   1],
        [  3,   1,   1]],

       [[171, 163, 156],
        [172, 164, 157],
        [174, 166, 159],
        ...,
        [  3,   1,   1],
        [  3,   1,   1],
        [  3,   1,   1]],

       [[173, 167, 160],
        [174, 168, 161],
        [175, 169, 162],
        ...,
        [  3,   1,   1],
        [  3,   1,   1],
        [  3,   1,   1]],

       ...,

       [[ 10,   8,   7],
        [ 13,  11,  10],
        [ 13,  11,  10],
        ...,
        [ 40,  30,  30],
        [ 39,  29,  29],
        [ 38,  28,  28]],

       [[ 10,   8,   7],
        [ 13,  11,  10],
        [ 13,  11,  10],
        ...,
        [ 40,  30,  30],
        [ 39,  29,  29],
        [ 38,  28,  28]],

       [[ 10,   8,   7],
        [ 13,  11,  10],
        [ 13,  11,  10],
        ...,
        [ 40,  30,  30],
        [ 39,  29,  29],
        [ 38,  28,  28]]

In [ ]:
cv2.imshow("image", flipped)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import numpy as np
import cv2
img = cv2.imread('/Users/luizeduardosantos/Documents/Turing/projeto-trainee-cv/Dataset Trainee Oficial Top/Darth Vader/0c7ed5773df0c92a95a543eeba9a077979a5256a.jpg', 1)
#np.fliplr(img)
#np.flipup(img)

#code=np.random.choice([-1,0,1])
#cv2.flip(img,code)

In [ ]:
#rotação, brilho, zoom
linhas = np.shape(img)[0]
colunas = np.shape(img)[1]

center= (np.random.randint(linhas*(9/20),linhas*(11/20)),
         np.random.randint(colunas*(9/20),colunas*(11/20)))
angle= (np.random.random()*360)
scale= (np.random.random()/10)+0.95
M = cv2.getRotationMatrix2D(center,angle,scale)
img_rot = cv2.warpAffine(img,M,(colunas,linhas))

In [ ]:
cv2.imshow("image", img_rot)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
alpha = 1. #contraste
beta = 0 #brilho
new_img = np.empty(np.shape(img))
for y in range(img.shape[0]):
    for x in range(img.shape[1]):
        for c in range(img.shape[2]):
            new_img[y,x,c] = np.clip(alpha*img[y,x,c] + beta, 0, 255)
cv2.imshow("image", new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()